# Generated by Django 2.2.28 on 2022-09-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220912_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Текст жалобы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flat',
            name='has_balcony',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Наличие балкона'),
        ),
    ]
