# Generated by Django 2.2.28 on 2022-09-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20220914_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='content',
            new_name='text',
        ),
    ]
